### ISSUE TITLE
0 CUDA Error

### ISSUE THREAD

**Issue by burak052** [leggedrobotics/darknet_ros#288]
`0 CUDA Error: no CUDA-capable device is detected
CUDA Error: no CUDA-capable device is detected: Bad file descriptor
[darknet_ros-1] process has died [pid 15933, exit code -6, cmd /home/zaphkiel/catkin_ws/devel/lib/darknet_ros/darknet_ros __name:=darknet_ros __log:=/home/zaphkiel/.ros/log/c17b16f2-4839-11eb-aa2e-f0038c4d290f/darknet_ros-1.log].
log file: /home/zaphkiel/.ros/log/c17b16f2-4839-11eb-aa2e-f0038c4d290f/darknet_ros-1*.log

`
how can i fix this error?

![Ekran Görüntüsü - 2020-12-27 15-07-03](https://user-images.githubusercontent.com/67500703/103170430-35fb1700-4855-11eb-84e7-e2e01822307d.png)

**Comment by TumVink** [comment]
Hey. Same issue how to solve it?

**Comment by tomlankhorst** [comment]
Does `nvidia-smi` show you any results?

**Comment by patrick1bauer** [comment]
nvidia-smi no result for me

**Comment by RotorBoy2020** [comment]
I am having this same error as well. I am using VMWare with Ubuntu 18.04. Is there a way to run darknet without needing a CUDA GPU?

**Comment by leeisack** [comment]
I'm having the same problem, the nvidia-smi output comes out like this


![스크린샷, 2021-04-20 11-23-34](https://user-images.githubusercontent.com/52061393/115328179-21a7a500-a1cb-11eb-9baa-5430fd7688fc.png)

**Comment by tomlankhorst** [comment]
If you don't have / want to use a NVidia GPU, don't install CUDA on your system. 

Try commenting out line 17 https://github.com/leggedrobotics/darknet_ros/blob/master/darknet_ros/CMakeLists.txt#L17 of the CMakeLists.txt when you get CUDA errors but you don't have a CUDA GPU. 

If you do see output, like @leeisack , then you actually should not get this error. Try running darknet with the following environment variable set:

[`CUDA_VISIBLE_DEVICES=0`](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/), this will instruct CUDA to only make the first device visible. 

(In a single bash session for example, run `export CUDA_VISIBLE_DEVICES=0`)

**Comment by enekorodriguezplaza** [comment]
Hi, I have the same issue. nvidia-smi works, like for @leeisack, but doing hat @tomlankhorst suggested did not work. Any other suggestions?

**Comment by ThornsOoO** [comment]
If you don't want to use GPU, you can delete "find_ package(CUDA QUIET)" in Cmakelists

**Comment by leeisack** [comment]
I solved this, thank you

**Comment by enekorodriguezplaza** [comment]
@leeisack could you please share how you solved it?

**Comment by leeisack** [comment]
Well... I don't know we build the same problem first. However, in the case of me, the driver was automatically installed when cuda was installed, but if you do this, the latest driver is installed and the version of cuda is automatically increased. So, I installed the driver and cuda by setting the correct version separately.

**Comment by tomlankhorst** [comment]
@leeisack 
Thank you for your reply. Can you maybe share what you mean with "So, I installed the driver and cuda by setting the correct version separately."? Maybe you can provide us with the commands you used.

**Comment by tayfurg7** [comment]
i still have the same problem.
![image](https://user-images.githubusercontent.com/81748619/119349318-b5770000-bca6-11eb-89cb-d422c41d5ed1.png)
my nvidia-smi;
![image](https://user-images.githubusercontent.com/81748619/119349379-caec2a00-bca6-11eb-8034-46af511c034e.png)

**Comment by leeisack** [comment]
I didn't use a special method... It was solved by installing the driver according to the gpu version I am using. It seems that cuda and cudnn are installed according to the driver. So, in my case, I wanted to install the old versions of cuda and cudnn, but since the gpu is gtx1080, relatively latest version of the driver was installed and cuda and cudnn were automatically upgraded.
As a result, it was resolved by completely removing cuda, driver, and cudnn, and installing all three by entering the desired version directly. There is nothing I can advise other than this...

**Comment by tayfurg7** [comment]
I dont know which version required to be installed according to my gpu.
When i choose GPU as hardware acceleration from notebook settings, gpu is not connected to backend. Can be it caused of this problem?
________________________________

**Comment by PankaChakma** [comment]
> i still have the same problem. ![image](https://user-images.githubusercontent.com/81748619/119349318-b5770000-bca6-11eb-89cb-d422c41d5ed1.png) my nvidia-smi; ![image](https://user-images.githubusercontent.com/81748619/119349379-caec2a00-bca6-11eb-8034-46af511c034e.png)

did you solve the issue?
